require: 
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['^(\s*#)']

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
